name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

      - name: Deploy
        working-directory: docs/.vitepress/dist
        run: |
          git init
          git checkout -b gh-pages
          git add -A
          git -c user.name='coder-lzh' -c user.email='657083979@qq.com' commit -m '测试一下'
          git remote add origin https://github.com/coder-lzh/vitepressDemo2.git
          git push origin gh-pages -f -q
